In [ ]:
#1. Import the Numpy package under the name np
import numpy as np

In [64]:
#2. Create a null vector of size 10
x= np.zeros(10 , dtype=int)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [65]:
#3. Create a null vector of size 10 but the fifth value which is 1
x[4]=1
print(x)

[0 0 0 0 1 0 0 0 0 0]


In [16]:
#4. Create a vector with values ranging from 10 to 49
b=np.arange(10,49)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [66]:
#5. Reverse a vector (the first element becomes last) - my original method by using zero vector
a=np.arange(1,11)
c=np.zeros(10 ,dtype=int)
print("This is the original vector :" , a)
i=0
j=9
while (i < 11) and (j >= 0):
    c[i] = a[j]
    i+=1
    j-=1
else :
     print("This is the reverse vector:" , c)



This is the original vector : [ 1  2  3  4  5  6  7  8  9 10]
This is the reverse vector: [10  9  8  7  6  5  4  3  2  1]


In [39]:
#found from web a shortcut method to reverse
res = a[::-1]
print("This is the reverse vector using shortcut method:" ,res)

This is the reverse vector using shortcut method: [10  9  8  7  6  5  4  3  2  1]


In [41]:
#found from web using flipud method to reverse
res1=np.flipud(a)
print("This is the reverse vector using flipud method :" ,res1)

This is the reverse vector using flipud method : [10  9  8  7  6  5  4  3  2  1]


In [ ]:
# 6. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(0,9).reshape(3,3)
print("This is a 3X3 matrix with values ranging from 0-8 :\n", matrix)

In [20]:
# 7. Find indices of non zero elements from [1,2,0,0,4,0] as per my logic
my_array= np.array([1,2,0,0,4,0])
len_array = len(my_array)
# print(len_array)
i=0
while (i < (len_array)):
    if(my_array[i] != 0):
      print("Indice", i , "has a non zero element")
    i+=1


Indice 0 has a non zero element
Indice 1 has a non zero element
Indice 4 has a non zero element


In [17]:
# found this code on the web for finding non zero element indices
result = np.where(my_array != 0)[0]
print("Original Array : ", my_array)
print("Indices with non zero elements :" , result)

Original Array :  [1 2 0 0 4 0]
Indices with non zero elements : [0 1 4]


In [23]:
# 8. Create a 3x3x3 array with random values
x=np.random.random((3,3,3))
print(x)

[[[0.65493038 0.36469021 0.50860251]
  [0.64407983 0.71793763 0.77781951]
  [0.20890844 0.06693729 0.41153697]]

 [[0.49854221 0.12171975 0.9011605 ]
  [0.33624123 0.70456536 0.58140076]
  [0.80486063 0.19102548 0.20319778]]

 [[0.24565737 0.74661284 0.62462638]
  [0.91313238 0.80349028 0.01546664]
  [0.83747745 0.64772782 0.94997225]]]


In [33]:
# 9. Create a random vector of size 30 and find the mean value
y=np.random.random(30)
print("Random vector of size 30:\n", y)
array_mean = round(np.mean(y),3)
print("\n The mean value of the random array is :", array_mean)

Random vector of size 30:
 [0.38888782 0.71960015 0.83925502 0.38009134 0.97483924 0.5353642
 0.12815124 0.03793292 0.55264375 0.98103559 0.08259764 0.50196338
 0.88365256 0.34234386 0.10725851 0.8170361  0.70452653 0.32860682
 0.0570116  0.28037798 0.19764442 0.18814379 0.53495939 0.88648587
 0.8021132  0.03047882 0.71733037 0.91539396 0.18884442 0.80474168]

 The mean value of the random array is : 0.497


In [63]:
# 10. Create a 2d array with 1 on the border and 0 inside
z=np.full((5,5),0)
print("This is the 2D array created with elements value as 0 \n \n", z)
i=0
j=0

for i in range(5):
   
        for j in range(5):
            if ((i==0) or (i==4) or (j==0) or (j==4)):
                z[i,j] = 1
                #print("updated" , i ,j ,z[i,j])
            j+=1
        else :
            i=+1

print("\n This the 2d array with 1 on the border and 0 inside \n \n", z) 


This is the 2D array created with elements value as 0 
 
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

 This the 2d array with 1 on the border and 0 inside 
 
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [70]:
# 11. Create an 8x8 matrix and fill it with a checkerboard pattern

z=np.full((8,8),0)
print("This is a 8x8 matrix created with elements value as 0 \n \n", z)
i=0
j=0

for i in range(8):
   
        for j in range(8):
            if () (j in (0,2,4,6)):
                z[i,j] = 1
                #print("updated" , i ,j ,z[i,j])
            j+=1
        else :
            i=+1
            j=+1

print("\n This the 2d array with 1 on the border and 0 inside \n \n", z) 


This is a 8x8 matrix created with elements value as 0 
 
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

 This the 2d array with 1 on the border and 0 inside 
 
 [[1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]]
